org: vkunssec
app: simple-serverless
service: simple-serverless
frameworkVersion: "3"

plugins:
    - serverless-esbuild
    - serverless-offline-sqs
    - serverless-offline
    - serverless-stage-manager

provider:
    name: aws
    runtime: nodejs18.x
    region: ${opt:region, "sa-east-1"}
    stage: ${opt:stage, "development"}
    environment:
        STAGE: ${self:provider.stage}
        CONSUMER_QUEUE_URL: ${self:custom.${self:provider.stage}.CONSUMER_QUEUE_URL}
        ENDPOINT: ${self:custom.${self:provider.stage}.ENDPOINT}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - lambda:*
                      - sqs:*
                  Resource: "*"

resources:
    Resources:
        consumer: ${file(resources/queue/consumer.yml):consumer}
        consumerDLQ: ${file(resources/queue/consumer.yml):consumerDLQ}

    Outputs:
        consumerArn: ${file(resources/queue/consumer.yml):Outputs.consumerArn}
        consumerUrl: ${file(resources/queue/consumer.yml):Outputs.consumerUrl}

functions:
    healthcheck:
        handler: ./src/lambda/healthcheck.handler
        events:
            - httpApi:
                  path: /api/healthcheck
                  method: GET

    producer:
        handler: ./src/lambda/producer.handler
        events:
            - httpApi:
                  method: POST
                  path: /produce-message

    consumer:
        handler: ./src/queue/consumer.handler
        events:
            - sqs:
                  arn: ${self:custom.consumer.arn}
                  batchSize: 1

custom:
    stages:
        - development
        - staging
        - production

    development:
        ENDPOINT: "http://localhost:9324"
        CONSUMER_QUEUE_URL: ${self:service}-${self:provider.stage}-consumer
    staging:
        ENDPOINT: ""
        CONSUMER_QUEUE_URL: ${self:custom.consumer.url}
    production:
        ENDPOINT: ""
        CONSUMER_QUEUE_URL: ${self:custom.consumer.url}

    consumer:
        arn: !GetAtt consumer.Arn
        url: !Ref consumer

    serverless-offline-sqs:
        autoCreate: true
        apiVersion: "2012-11-05"
        endpoint: http://0.0.0.0:9324
        region: us-east-1
        accessKeyId: doesnt_matter
        secretAccessKey: doesnt_matter
        skipCacheInvalidation: false
